sudo: false
language: python

python:
    - '3.6'
    - '3.7'
    - '3.8'
    - pypy3


branches:
  only:
  - master
  - release

install:
    - pip install tox-travis
    - pip install pygraphviz
    - pip install regex

script:
    tox
